"""
Pydantic models for the Agent Pipeline service.
"""

from .claim import (
    BronzeClaimRecord,
    ClaimComplexity,
    ClaimData,
    ClaimStatus,
    ClaimSummary,
    ClaimType,
    GoldClaimRecord,
    PetInfo,
    PolicyInfo,
    ProviderInfo,
    SilverClaimRecord,
)
from .events import (
    AgentCompletedEvent,
    AgentFailedEvent,
    AgentStartedEvent,
    AlertCreatedEvent,
    DecisionMadeEvent,
    EventBatch,
    EventSeverity,
    EventSubscription,
    EventType,
    PipelineEvent,
    StepCompletedEvent,
    StepReasoningEvent,
    StepStartedEvent,
    ToolCalledEvent,
    ToolResultEvent,
    WebSocketMessage,
)
from .pipeline import (
    AgentState,
    AgentStatus,
    PipelineHistoryRequest,
    PipelineHistoryResponse,
    PipelineMetrics,
    PipelineRunSummary,
    PipelineStage,
    PipelineState,
    PipelineStatus,
    TriggerRequest,
    TriggerResponse,
)

__all__ = [
    # Claim models
    "ClaimType",
    "ClaimStatus",
    "ClaimComplexity",
    "ClaimData",
    "PetInfo",
    "PolicyInfo",
    "ProviderInfo",
    "BronzeClaimRecord",
    "SilverClaimRecord",
    "GoldClaimRecord",
    "ClaimSummary",
    # Pipeline models
    "PipelineStage",
    "PipelineStatus",
    "AgentStatus",
    "TriggerRequest",
    "TriggerResponse",
    "AgentState",
    "PipelineState",
    "PipelineRunSummary",
    "PipelineHistoryRequest",
    "PipelineHistoryResponse",
    "PipelineMetrics",
    # Event models
    "EventType",
    "EventSeverity",
    "PipelineEvent",
    "AgentStartedEvent",
    "AgentCompletedEvent",
    "AgentFailedEvent",
    "StepStartedEvent",
    "StepCompletedEvent",
    "StepReasoningEvent",
    "ToolCalledEvent",
    "ToolResultEvent",
    "DecisionMadeEvent",
    "AlertCreatedEvent",
    "WebSocketMessage",
    "EventSubscription",
    "EventBatch",
]
